# Generated by Django 2.2 on 2019-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('actors', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
